name: ci

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} / ghc-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:
          - 8.10.1
        cabal:
          - 3.2.0.0
        os:
          - ubuntu-latest
          - macos-10.15
          - windows-latest

    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Haskell setup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cabal update and install
        run: |
          cabal update
          cabal install --installdir public --install-method copy

      - if: matrix.os != 'windows-latest'
        name: Zip / Unix
        run: zip -r public/blksc3-${{ runner.os }}.zip public/blksc3

      - if: matrix.os == 'windows-latest'
        name: Zip / Windows
        run: powershell Compress-Archive -Path public/blksc3.exe -DestinationPath public/blksc3-${{ runner.os }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_id }}
          files: public/blksc3-${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
